apiVersion: v1
kind: Namespace
metadata:
  name: opendine-dev
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: envread-settings
  namespace: opendine-dev
data:
  app.config.json: |-
    {
      "environment": "Production",
      "serviceA": "https://my-apps.google.com/service-a",
      "serviceB": "https://my-apps.google.com/service-b",
      "serviceC": "https://my-apps.google.com/service-c",
      "keyCloakUrl": "sso-dev.keycloak.com",
      "neato": "https://my-apps.neato.com/awesome123"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendine-api
  namespace: opendine-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendine-api
  template:
    metadata:
      labels:
        app: opendine-api
    spec:
      containers:
      - name: opendine-api
        image: acropendine.azurecr.io/opendine-api:1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "250Mi"
        volumeMounts:
          - name: envread-volume
            mountPath: /usr/share/nginx/html/assets/config/
      volumes:
      - name: envread-volume
        configMap:
          name: envread-settings
---
kind: Service
apiVersion: v1
metadata:
  name: opendine-api
  namespace: opendine-dev
  labels:
    app: opendine-api
spec:
  type: LoadBalancer
  selector:
    app: opendine-api
  ports:
  # Port mapped to in K8s
  - port: 80

    protocol: TCP
    # Port exposed by container
    targetPort: 8080
